# Generated by Django 4.2.6 on 2024-01-17 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_earnings_description_dashboard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earnings',
            name='dashboard',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.dashboard'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='dashboard',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.dashboard'),
        ),
    ]
