# Generated by Django 4.2.6 on 2024-01-17 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_earnings_dashboard_alter_expense_dashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earnings',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.dashboard'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.dashboard'),
        ),
    ]
